site:
  title: OpenMSL
  url: https://persival-gmbh.github.io/asciidoc-test
  start_page: OpenMSL::index.adoc 
content:
  sources: 
  - url: https://github.com/Persival-GmbH/asciidoc-test.git
    branches: HEAD
    edit_url: false
    start_path: doc
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #url: https://code.asam.net/common/antora-ui/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files: ./supplemental_ui
