= Organization

This GitHub organization is maintained by the https://www.asc-s.de/[Automotive Solution Center for Simulation e.V.] - a non-profit industry club registered in Germany.
The main focus of its activities is the concentration of expertise from automotive and supply industry, software and hardware manufacturers, engineering service providers and research institutes.
The asc(s brings together key leaders from the industry with the best and most renowned scientists in the field of virtual vehicle development. Its members benefit from a worldwide unique research
and development landscape with special focus on high-performance computing, driving simulation and digitalization.

The https://envited.market/[ENVITED Research Cluster] is an initiative to create the Environment for Virtual Test Drive in a collaborative way, defining a methodology for a standard data based virtual proof of validation.
Virtual validation is becoming an essential part of development processes for highly automated driving (HAD) functions. Standards for model and system interchange are vital for cross-company and cross-domain virtual
integration and simulation of HAD functions.


## ASC(S e.V. Governance Rules

The collaboration of contributors in this GitHub organization is organized under the umbrella of the Automotive Solution Center for Simulation e.V.
In this community the general xref:governance_rules.adoc[Governance Rules] needed to fulfill industry compliance regulations are set.

## Code of Conduct

As a community we need to define how we want to interact with each other respectfully and make sure that we create an inclusive environment that encourages contributions.
For this reason OpenMSL has a clear https://github.com/openMSL/.github/blob/main/CODE_OF_CONDUCT.md[Code of Conduct] that applies to everyone. Read https://opensource.guide/code-of-conduct/[here] why we need a code of conduct.
A modified version of https://www.contributor-covenant.org/[this] document is currently in use.

## Contributing Guidelines

Thanks for your interest in contributing! There are many ways to contribute to this project.
Get started https://github.com/openMSL/.github/blob/main/CONTRIBUTING.md[here].

## PR and Issue Templates

This repository also defines the standard issue and pull request templates valid for the overall organization.

## Licensing

The open-source material to be contributed must be licensed under a common open-source license as listed on https://opensource.org/[opensource.org] and documented in a LICENSE file.

The license tells you what rights you have as a developer, provided by the copyright holder.
It is important that the contributor fully understands the licensing rights and agrees to them. Sometimes the copyright holder isn’t the contributor, such as when the contributor is doing work on behalf of a company.

## Public organization profile

The profile information is described in https://github.com/openMSL/.github/blob/main/profile/README.md[.github/profile/README.md] and displayed on the organization main page.
Read the corresponding GitHub https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile[documentation] for more information on organization profiles.
