= CL 1: Code Verification

Credibility assessment level 1 contains multiple different tests for code quality.
In the first test, linters are used to ensure general quality of code and documentation.
In the example linked below, linters for C++ code, markdown files, and xml files such as SRMD and modelDescription are implemented.
Further linters have to be added, if additional programming languages are used.
In the second test, the model is build using cmake.
The third test category runs unit tests defined for the individual model.

An implementation of the GitHub action for this credibility assessment level can be found in the https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/.github/workflows/cl1.yml[sensor model template repository].

## CL 1.1: Linter

These tests consist of linters checking the formatting against style guides for code, markdown and xml.

### C++ Linter

C++ code is checked with clang according to the clang-format and clang-tidy files in the repository.
It is mandatory for every code repository to provide these config files.
As a best practice, https://github.com/eklitzke/clang-format-all[clang-format-all] can be used to automatically format all C++ files in the repository.
Be aware, that formatting might break functionality, e.g. by a different order of includes.
Be sure to check after formatting.

An implementation of the corresponding GitHub action can be found in the https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/.github/workflows/cpp-linter.yml[sensor model template repository].

### Markdown Linter

Markdown files are checked by a markdown linter according to https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md[these] basic rules.

An implementation of the corresponding GitHub action can be found in the https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/.github/workflows/markdown.yml[sensor model template repository].
It also contains an example https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/.github/workflows/markdownlint.json[markdownlint.json] specifying variations of the applied rules.

### SRMD Validator

Every model repository SHALL include an https://pmsfit.github.io/SSPTraceability/master/#_srmd[SRMD file] conforming to the https://pmsfit.github.io/SSPTraceability/master/[SSP tracability] process.
This file is checked against the https://github.com/PMSFIT/SSPTraceability[SRMD XML schema].

## CL 1.2: Build

These tests check if the model can be build and the built FMU is compliant with the https://github.com/modelica/fmi-standard[FMI standard].

### Cmake

This test checks if cmake runs without errors and the model can be built with all necessary dependencies, such as OSI with Protobuf.

An implementation of the corresponding GitHub action can be found in the https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/.github/workflows/build.yml[sensor model template repository].

### FMU Compliance Checker

The official https://github.com/modelica-tools/FMUComplianceChecker[FMU Compliance Checker] by Modelica is used to check if the built FMU is compliant with the https://github.com/modelica/fmi-standard[FMI standard].
This includes checking the binaries as well as included xml files such as the modelDescription.

Since the FMU Compliance Checker does not seem to be further maintained, https://github.com/CATIA-Systems/FMPy[FMPy] is used as a second validation tool.

## CL 1.3 Unit Tests

Models SHALL include individual unit tests.
The tests SHALL be located in a folder _test/unit_ which MUST include the applied unit test library (e.g. https://github.com/google/googletest[GoogleTest]).
Unit tests have to be custom to the implementation of the individual model.
Therefore, no standard unit tests are part of this test pipeline.

However, some examples can be found in the https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main/test/unit[sensor model template repository].